### PR TITLE
contrib/99designs/gqlgen: fix introspection query detection by checking Operation.Name

### LINKED ISSUE #3085: [BUG] GQLgen Tracer - Introspection query is not always being filtered
We are using GQL Tracer for our application. 
We want to reduce the amount of noise so have enabled the `WithoutTraceIntrospectionQuery` Option.

However, the tracer sometimes collects fields under the Introspection query.
We have confirm:
- Playground comes with `github.com/99designs/gqlgen`: Filtered properly
- Retool introspection (https://www.retool.com) : Does not filtered

We have configured the tracer as follow:

```go
func createGQLHandler(	schema graphql.ExecutableSchema) http.Handler {
	h := handler.New(schema)
	h.AddTransport(transport.Options{})
	h.AddTransport(transport.POST{})
	h.Use(extension.Introspection{})
	h.SetRecoverFunc(func(ctx context.Context, err interface{}) error {
		logger.Error("graphql panic", "err", err)
		debug.PrintStack()
		return gqlerror.Errorf("internal system error")
	})
	h.SetErrorPresenter(func(ctx context.Context, err error) *gqlerror.Error {
		logger.Error("graphql error", "err", err)
		return graphql.DefaultErrorPresenter(ctx, err)
	})
	if config.DD_TRACE_ENABLED {
		t := gqlgentrace.NewTracer(
			gqlgentrace.WithAnalytics(true),
			gqlgentrace.WithServiceName(logging.DDServiceName),
			gqlgentrace.WithoutTraceIntrospectionQuery(),
			gqlgentrace.WithoutTraceTrivialResolvedFields(),
		)
		h.Use(t)
	}
	httpAuthware, gqlAuthware := authenticator.NewAuthMiddleware(skipAudCheck)
	h.AroundOperations(gqlAuthware)
	return httpAuthware(h)
}
```

**Version of dd-trace-go**
1.70.3

**Describe what happened:**
Query comes from Retool traced all the fields under it.

Image

**Describe what you expected:**
- All fields under any query operation named `IntrospectionQuery` shall not be traced.

**Steps to reproduce the issue:**
- Login Retool
- Connecting any resource with above tracer.
- Creating a query to the GQL resource and trigger the Introspection Query.

**Additional environment details (Version of Go, Operating System, etc.):**

### PR DESCRIPTION
**Pull request by LamineKouissi**
### What does this PR do?
contrib/99designs/gqlgen: fix introspection query detection by checking Operation.Name

### Motivation
InterceptField() relied on OperationName to identify introspection queries. This was insufficient as valid introspection queries can have an unset OperationName while Operation.Name is set to IntrospectionQuery.

Could Fix #3085

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] [System-Tests](https://github.com/DataDog/system-tests/) covering this feature have been added and enabled with the va.b.c-dev version tag.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.
- [ ] Add an appropriate team label so this PR gets put in the right place for the release notes.
- [ ] Non-trivial go.mod changes, e.g. adding new modules, are reviewed by @DataDog/dd-trace-go-guild.
- [ ] For internal contributors, a matching PR should be created to the `v2-dev` branch and reviewed by @DataDog/apm-go.

Unsure? Have a question? Request a review!

### CODE REVIEW

File: contrib/99designs/gqlgen/tracer.go [hunk 1]
```diff
@@ -244,6 +244,13 @@ func serverSpanName(octx *graphql.OperationContext) string {
 	return namingschema.OpNameOverrideV0(namingschema.GraphqlServer, nameV0)
 }
 
+func isIntrospectionQuery(octx *graphql.OperationContext) bool {
+	if octx != nil && octx.Operation != nil {
```
Comment (darccio) [inline contrib/99designs/gqlgen/tracer.go:248]: @LamineKouissi `octx` seems to be guaranteed to be not nil by `gqlgen`: https://github.com/99designs/gqlgen/blob/master/graphql/context_operation.go#L61

`octx.Operation`'s nil check is fine.

**Review by darccio — CHANGES_REQUESTED** [review]

File: contrib/99designs/gqlgen/tracer.go (hunk 1 above)
Comment (LamineKouissi) [reply contrib/99designs/gqlgen/tracer.go:248]: I was planning not to check it initially, but `serverSpanName()` checks `octx`, which is why I added the check

**Review by rarguelloF — APPROVED** [review]

**Comment by LamineKouissi** [comment]
Hi @darccio @rarguelloF 
Could you please let me know if any changes are needed? If everything looks good, I’d appreciate if you merge it.

**Review by rarguelloF — APPROVED** [review]

**Comment by LamineKouissi** [comment]
Hi @rarguelloF, do I need to merge main into my PR every time there's a change, or can you handle that during the PR merge?

**Review by darccio — APPROVED** [review]

**Comment by darccio** [comment]
Thanks @LamineKouissi for contributing this.
