### PR TITLE
ddtrace/opentelemetry: add RWMutex to handle concurrent calls to setters

### LINKED ISSUE #2518: [BUG] fatal error: concurrent map writes (*span).SetAttributes
**Version of dd-trace-go**

v1.59.0

**Describe what happened:**

Calling span.SetAttributes concurrently results in `fatal error: concurrent map writes`

**Describe what you expected:**
The span does not seem thread-safe for concurrent reads and writes and it is unclear whether this is the intended behavior.

**Steps to reproduce the issue:**

```
	ctx, span = tracer.Start(ctx, "test")
	defer span.End()

	numberOfWorkers := 100
	workerIDs := []int{}
	for i := 0; i < numberOfWorkers; i++ {
		workerIDs = append(workerIDs, i)
	}
	_, err = collections.ParallelWorkerMapE(workerIDs, func(i int) (any, error) { // this is a custom method that loops over a slice and runs a function in parallel
		for {
			span.SetAttributes(attribute.Float64("workerID", float64(i)))
		}
	}, numberOfWorkers)
	if !assert.NoError(t, err) {
		return
	}
```

**Additional environment details (Version of Go, Operating System, etc.):**
go version go1.20 linux/amd64

### PR DESCRIPTION
**Pull request by darccio**
### What does this PR do?

Fixes #2518.

### Motivation

Making sure OTel spans can be used concurrently, as our `tracer.Span`.

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] [System-Tests](https://github.com/DataDog/system-tests/) covering this feature have been added and enabled with the va.b.c-dev version tag.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.
- [ ] Add an appropriate team label so this PR gets put in the right place for the release notes.
- [ ] Non-trivial go.mod changes, e.g. adding new modules, are reviewed by @DataDog/dd-trace-go-guild.

For Datadog employees:

- [ ] If this PR touches code that handles credentials of any kind, such as Datadog API keys, I've requested a review from `@DataDog/security-design-and-guidance`.
- [ ] This PR doesn't touch any of that.

Unsure? Have a question? Request a review!

### CODE REVIEW

File: ddtrace/opentelemetry/span.go [hunk 1]
```diff
@@ -38,10 +40,14 @@ type span struct {
...
 
 func (s *span) SetName(name string) {
+	s.mu.Lock()
+	defer s.mu.Unlock()
 	s.attributes[ext.SpanName] = strings.ToLower(name)
 }
 
 func (s *span) End(options ...oteltrace.SpanEndOption) {
+	s.mu.Lock()
+	defer s.mu.Unlock()
```
Comment (darccio) [inline ddtrace/opentelemetry/span.go:50]: It feels weird to lock here, as there will be a second mutex locked inside `s.DD.Finish`. But I found another panic if I don't lock from the beginning of the function.

Comment (darccio) [reply ddtrace/opentelemetry/span.go:50]: I understand this is the recommended pattern, as it's guaranteed to unlock. We could lock after the `s.finished` conditional, but then we'll be accessing a field that can be changed concurrently too.

File: ddtrace/opentelemetry/span.go [hunk 2]
```diff
@@ -157,6 +163,8 @@ type statusInfo struct {
 // value before (OK > Error > Unset), the code will not be changed.
 // The code and description are set once when the span is finished.
 func (s *span) SetStatus(code otelcodes.Code, description string) {
+	s.mu.Lock()
```
[the remark this answers is not in the document]
Comment (darccio) [reply ddtrace/opentelemetry/span.go:166]: Yes, it failed without it.

File: ddtrace/tracer/tracer_test.go [hunk 3]
```diff
@@ -922,6 +922,28 @@ func TestTracerBaggageImmutability(t *testing.T) {
...
+			span.SetBaggageItem("val", fmt.Sprintf("%d", val))
+
+			traceContext := map[string]string{}
+			_ = tr.Inject(span.Context(), TextMapCarrier(traceContext))
+		}(i)
+	}
+
+	wg.Wait()
+}
+
```
Comment (katiehockman) [inline ddtrace/tracer/tracer_test.go:946]: @darccio when I run this test against main I can't get the test to fail with `-race` enabled, no matter how many runs I give it. It looks like `newTracer()` doesn't set up the tracer in the right way to trigger this. I will make a commit with the necessary changes that make this fail consistently for me locally.

The other test, `TestConcurrentSetAttributes`, fails easily for me.

File: ddtrace/tracer/textmap.go [hunk 4]
```diff
@@ -349,6 +349,8 @@ func (p *propagator) injectTextMap(spanCtx ddtrace.SpanContext, writer TextMapWr
 	if !ok || ctx.traceID.Empty() || ctx.spanID == 0 {
 		return ErrInvalidSpanContext
 	}
+	ctx.mu.Lock()
+	defer ctx.mu.Unlock()
```
Comment (katiehockman) [inline ddtrace/tracer/textmap.go:353]: This is just to protect `ctx.baggage`, right? In that case, we should just use `(c *spanContext) ForeachBaggageItem` which handles the lock for us. That will also help us hold the lock for as little time as possible.

Comment (katiehockman) [reply ddtrace/tracer/textmap.go]: I went ahead and pushed that change.

**Comment by katiehockman** [comment]
The changes look good to me, so I'll approve them. However, I made a couple of commits, so I'd like @dianashevchenko to look this over on Monday.

File: ddtrace/opentelemetry/span.go (hunk 1 above)
Comment (katiehockman) [reply ddtrace/opentelemetry/span.go:50]: That's what we do for `span.finish`, so that should be fine? https://github.com/DataDog/dd-trace-go/blob/main/ddtrace/tracer/span.go#L513-L514

**Review by katiehockman — APPROVED** [review]

**Review by dianashevchenko — APPROVED** [review]

**Comment by darccio** [comment]
Thanks @katiehockman & @dianashevchenko!
