### PR TITLE
fix(internal/remoteconfig): allow Remote Config singleton to be reentrant

### LINKED ISSUE #4111: [BUG]: duplicate calls to `tracer.Start` permanently disable remote config
### Tracer Version(s)

v1.74.7 & v2.3.1

### Go Version(s)

go 1.24.7

### Bug Report

When calling `tracer.Start` more than once, `remoteconfig.Stop` gets called, and then all subsequent start calls are noops. 

The `Start` call should theoretically be safe to happen more than once.

https://github.com/DataDog/dd-trace-go/blob/74efb9e9e7112328ff413810b11c2e2486d21a29/ddtrace/tracer/tracer.go#L200-L203
https://github.com/DataDog/dd-trace-go/blob/74efb9e9e7112328ff413810b11c2e2486d21a29/ddtrace/tracer/tracer.go#L222
https://github.com/DataDog/dd-trace-go/blob/74efb9e9e7112328ff413810b11c2e2486d21a29/ddtrace/tracer/globaltracer.go#L15-L18
https://github.com/DataDog/dd-trace-go/blob/74efb9e9e7112328ff413810b11c2e2486d21a29/ddtrace/internal/globaltracer.go#L36
https://github.com/DataDog/dd-trace-go/blob/74efb9e9e7112328ff413810b11c2e2486d21a29/ddtrace/tracer/tracer.go#L865
https://github.com/DataDog/dd-trace-go/blob/74efb9e9e7112328ff413810b11c2e2486d21a29/internal/remoteconfig/remoteconfig.go#L239

### Reproduction Code

Call `tracer.Start` twice and notice that remote config won't work anymore.

### Error Logs

_No response_

### Go Env Output

_No response_

### PR DESCRIPTION
**Pull request by darccio**
### What does this PR do?

Models `internal/remoteconfig` package's behaviour to mirror how `SetGlobalTracer` behaves when calling `Start()` multiple times.

<s>AI generated PR.</s>

### Motivation

Fixes #4111.

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] [System-Tests](https://github.com/DataDog/system-tests/) covering this feature have been added and enabled with the va.b.c-dev version tag.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.
- [ ] New code is free of linting errors. You can check this by running `./scripts/lint.sh` locally.
- [ ] Add an appropriate team label so this PR gets put in the right place for the release notes.
- [ ] Non-trivial go.mod changes, e.g. adding new modules, are reviewed by @DataDog/dd-trace-go-guild.

Unsure? Have a question? Request a review!

### CODE REVIEW

File: internal/remoteconfig/remoteconfig.go [hunk 1]
```diff
@@ -195,65 +193,77 @@ func newClient(config ClientConfig) (*Client, error) {
...
+
+	if !internal.BoolEnv("DD_REMOTE_CONFIGURATION_ENABLED", true) {
+		// Don't start polling if the feature is disabled explicitly
+		return nil
+	}
+
+	// Stop existing client if running
+	if client != nil {
+		stopClientLocked()
+	}
```
Comment (felixge) [inline internal/remoteconfig/remoteconfig.go]: stopClientLocked() can be called unconditionally here, see stopClientLocked() for details.

```suggestion
	stopClientLocked()
```

File: ddtrace/tracer/remote_config_test.go [hunk 2]
```diff
@@ -772,7 +772,6 @@ func TestDynamicInstrumentationRC(t *testing.T) {
 	}
 
 	startRemoteConfig := func(t *testing.T, tracer *tracer) {
-		t.Cleanup(remoteconfig.Reset)
```
Comment (felixge) [inline ddtrace/tracer/remote_config_test.go:775]: ❓  I don't understand why the Reset calls are being removed.

**Review by felixge — COMMENTED** [review]
Gave this a light review, but mostly LGTM.

File: ddtrace/tracer/remote_config_test.go (hunk 2 above)
Comment (darccio) [reply ddtrace/tracer/remote_config_test.go:775]: `remoteconfig.Stop` absorbed the `client = nil` that was left behind after removing the `sync.Once` global variables.

File: internal/remoteconfig/remoteconfig.go (hunk 1 above)
Comment (darccio) [reply internal/remoteconfig/remoteconfig.go]: You are right. Fixed. I missed that during my review.

**Comment by darccio** [comment]
@codex review

File: internal/remoteconfig/remoteconfig.go [hunk 3]
```diff
@@ -195,65 +193,69 @@ func newClient(config ClientConfig) (*Client, error) {
...
+	select {
+	case <-client.stop:
+		log.Debug("remoteconfig: client stopped successfully")
+	case <-time.After(time.Second):
+		log.Debug("remoteconfig: client stopping timeout")
+	}
 	client = nil
-	startOnce = sync.Once{}
-	stopOnce = sync.Once{}
 }
```
[the remark this answers is not in the document]
Comment (darccio) [reply internal/remoteconfig/remoteconfig.go]: I took a different route.

**Comment by darccio** [comment]
@codex review

File: internal/remoteconfig/remoteconfig.go [hunk 4]
```diff
@@ -198,32 +196,34 @@ func newClient(config ClientConfig) (*Client, error) {
...
+		return err
+	}
+	go func() {
+		ticker := time.NewTicker(client.PollInterval)
+		defer ticker.Stop()
+
+		for {
+			select {
+			case <-client.stop:
+				close(client.stop)
```
Comment (kakkoyun) [inline internal/remoteconfig/remoteconfig.go]:
```suggestion
```

File: internal/remoteconfig/remoteconfig.go [hunk 5]
```diff
@@ -236,24 +236,25 @@ func Stop() {
...
-		case <-time.After(time.Second):
-			log.Debug("remoteconfig: client stopping timeout")
-		}
-	})
+	if !started.CompareAndSwap(true, false) {
+		// Return early if already stopped.
+		return
+	}
+	log.Debug("remoteconfig: gracefully stopping the client")
+	client.stop <- struct{}{}
```
Comment (kakkoyun) [inline internal/remoteconfig/remoteconfig.go]:
```suggestion
	close(client.stop)
```

File: internal/remoteconfig/remoteconfig.go [hunk 6]
```diff
@@ -198,32 +196,34 @@ func newClient(config ClientConfig) (*Client, error) {
...
-				case <-ticker.C:
-					client.Lock()
-					client.updateState()
-					client.Unlock()
-				}
+	if !internal.BoolEnv("DD_REMOTE_CONFIGURATION_ENABLED", true) {
+		// Don't start polling if the feature is disabled explicitly
+		return nil
+	}
+	if !started.CompareAndSwap(false, true) {
```
Comment (kakkoyun) [inline internal/remoteconfig/remoteconfig.go]: I think we should mark it started when we actually successfully start the client. And I would rather use a `mutex` instead of an atomic boolean. It is easier to reason about and control the in-flight starts.

**Review by kakkoyun — CHANGES_REQUESTED** [review]
Looking good.

I believe we can simplify by using a `mutex` and regular boolean and just closing the `client.stop` once.

File: internal/remoteconfig/remoteconfig.go (hunk 6 above)
Comment (mtoffl01) [reply internal/remoteconfig/remoteconfig.go]: ➕ to the  "when we actually successfully start the client" part

File: internal/remoteconfig/remoteconfig.go [hunk 7]
```diff
@@ -197,63 +196,75 @@ func newClient(config ClientConfig) (*Client, error) {
...
+		log.Debug("remoteconfig: client stopping timeout")
+	}
+	client = nil
+	started = false
 }
 
 // Reset destroys the client instance.
 // To be used only in tests to reset the state of the client.
 func Reset() {
 	client = nil
```
Comment (kakkoyun) [inline internal/remoteconfig/remoteconfig.go:276]: Now, these field accesses are unguarded.

**Review by kakkoyun — CHANGES_REQUESTED** [review]
We need to guard the `Reset`, I believe.

One other thing we can explore it to have an `atomic.Pointer` for the global client.

And embed the started logic into the `Client` since it has already have its own mutex. We can embed the logic in `Start()` into `Client.start()` and `Start` can proxy to it. 

We can swap the global client after a successful start.
WDYT?

File: internal/remoteconfig/remoteconfig.go (hunk 7 above)
Comment (darccio) [reply internal/remoteconfig/remoteconfig.go:276]: It's for tests, but I agree.

Comment (darccio) [reply internal/remoteconfig/remoteconfig.go:276]: Done in https://github.com/DataDog/dd-trace-go/pull/4118/commits/5f7502792798bdadd9ae6996b96dc4258608191e

**Comment by darccio** [comment]
> One other thing we can explore it to have an atomic.Pointer for the global client.

I tested this and it introduced too many changes. I think we need to find a better way to handle multiple products that run when the tracer is started.
