### PR TITLE
ddtrace/tracer: add WithHTTPClient and increase default HTTP timeout

### LINKED ISSUE #181: ddtrace/tracer: Client.Timeout exceeded
I'm running into a lot of `DataDog Tracer Errors` on the different services we run.

```
Datadog Tracer Error: Post http://dd-agent.kube-system:8126/v0.3/traces: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Datadog Tracer Error: unable to flush traces, lost 500 traces
```

This issue occurs on both of our clusters, both running Kubernetes: one self-managed, the other managed by Tectonic. We don't have connectivity issues between our services.
Please note that this issue is intermittent. We do receive traces on DataDog, but there's always a few that get lost.

```
# go version
go version go1.9.2 darwin/amd64
```

### PR DESCRIPTION
**Pull request by gbbr**
This change adds a new option `WithHTTPClient` and marks
`WithHTTPRoundTripper` as deprecated (now superseded). Additionally, the
default client timeout is increased to 2 seconds as it has proven to be
too short (see #181).

Closes #181

### CODE REVIEW

File: ddtrace/tracer/option.go [hunk 1]
```diff
@@ -243,12 +243,18 @@ func WithSampler(s Sampler) StartOption {
 	}
 }
 
-// WithHTTPRoundTripper allows customizing the underlying HTTP transport for
-// emitting spans. This is useful for advanced customization such as emitting
-// spans to a unix domain socket. The default should be used in most cases.
+// WithHTTPRoundTripper is deprecated. Please consider using WithHTTPClient instead.
```
Comment (knusbaum) [inline ddtrace/tracer/option.go:246]: Do we want to leave some of the original doc here alongside the deprecation warning?

I don't like when libraries remove older documentation because it makes it more difficult to figure out what an application using the library is *trying* to do. If the deprecated documentation is still in place, it's easier for me to tell without reading the library source what's going on.

I can see that leaving the documentation here might be seen by users as an endorsement for using the function. Maybe we can remove the `This is useful for` part, since that doesn't clarify what it does, and suggests its use.

```suggestion
// WithHTTPRoundTripper is deprecated. Please consider using WithHTTPClient instead.
// The function allows customizing the underlying HTTP transport for emitting spans. 
```

Comment (gbbr) [reply ddtrace/tracer/option.go:246]: Makes perfect sense.

**Comment by mingrammer** [comment]
I'm looking forward to this feature :)

**Comment by gbbr** [comment]
It'll be out in a few days
