### PR TITLE
contrib/gorilla/mux: add NoDebugStack option for datadog tracer

### LINKED ISSUE #615: contrib/gorilla/mux: Cannot disable stack traces on errors
The gorilla mux integration has some options to add options at span start but not span at finish, which I believe is necessary to disable stack traces.  We use another tool to handle errors, and we have some concern about the potential volume of such stack traces, so we'd prefer not to record a stack traces on each error.

### PR DESCRIPTION
**Pull request by ashanbrown**
By allowing span finish options to be passed to all of these integrations, we can disable things like stack traces on errors.  This code retains a slice of finishOptions that it can apply at the end of the span.  I'd suggest that this is more extensible better pattern than storing a boolean for noDebugStack.

Fixes #615

### CODE REVIEW

File: ddtrace/mocktracer/mockspan.go [hunk 1]
```diff
@@ -201,6 +201,9 @@ func (s *mockspan) Finish(opts ...ddtrace.FinishOption) {
 	if cfg.Error != nil {
 		s.SetTag(ext.Error, cfg.Error)
 	}
+	if cfg.NoDebugStack {
+		s.SetTag(ext.ErrorStack, "<mock no debug stack>")
```
Comment (gbbr) [inline ddtrace/mocktracer/mockspan.go]: Maybe this would be better
```suggestion
		s.SetTag(ext.ErrorStack, "<debug stack disabled>")
```
Otherwise it's hard to tell the difference between no debug stack (empty string) and `"<mock no debug stack>"`
