### PR TITLE
contrib/database/sql: implement driver.NamedValueChecker

### LINKED ISSUE #563: contrib/jmoiron/sqlx: uint64 argument error
I'm currently setting up the SQLx implementation of Datadog's tracer but am getting this error: `converting argument $1 type: uint64 values with high bit set`.

We're using the mysql driver - and haven't had any issues before implementing the datadog sqlx trace helper. It looks like it's trying to query w/ postgres almost ($1 looks very postgres vs ? in mysql parameterized query syntax).

This only seems to happen in tests. 

any ideas? is dd not using the underlying driver for some reason?

Here is a related issue with mysql implementing the underlying interface to prevent this uint64 error: https://github.com/go-sql-driver/mysql/issues/329

### PR DESCRIPTION
**Pull request by cgilmour**
This fixes a reported issue by implementing the `NamedValueChecker` on the tracer's wrapper for `driver.Conn`. 

From https://golang.org/pkg/database/sql/driver/#NamedValueChecker
>  The sql package checks for value checkers in the following order, stopping at the first found match: Stmt.NamedValueChecker, Conn.NamedValueChecker, Stmt.ColumnConverter, DefaultParameterConverter. 

Searching github, I wasn't able to find drivers that implemented `Stmt.NamedValueChecker`, so didn't attempt that.

Fixes #563

### CODE REVIEW

File: contrib/database/sql/sql_test.go [hunk 1]
```diff
@@ -55,6 +58,20 @@ func TestMySQL(t *testing.T) {
 		},
 	}
 	sqltest.RunAll(t, testConfig)
+	// additional test for uint64 values, supported by go-sql-driver/mysql
```
Comment (gbbr) [inline contrib/database/sql/sql_test.go]: This test seems a bit "snuck in" and out of place here. Can it maybe either have its own test or make it part of the `RunAll` test suite?

**Comment by devblueray** [comment]
Thank you Caleb!
